apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
  labels:
    app: orders 

spec:
  replicas: 1
  selector: 
    matchLabels: 
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
      containers:
        - name: orders
          image: ghcr.io/lordpangan/orders-service:local
          env:
            - name: INVENTORY_URL
              value: "http://inventory.sit.svc.cluster.local:8080"
            - name: PAYMENT_URL
              value: "http://payment.sit.svc.cluster.local:8080"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              initialDelaySeconds: 5
              periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              initialDelaySeconds: 10
              periodSeconds: 10
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
